# Generated by Django 5.0.4 on 2024-04-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(default='08:00:00')),
                ('data', models.DateField(default='2020-01-01')),
                ('descricao', models.TextField()),
                ('titulo', models.CharField(default='Reserva de Agendamento', max_length=50)),
                ('cliente', models.CharField(default=' ', max_length=50)),
                ('profissional', models.CharField(default=' ', max_length=50)),
                ('status', models.CharField(default='PENDENTE', max_length=8)),
            ],
        ),
    ]
